Shop structs and named vars
Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java pull request #105
Opened 2022-09-23 18:23 UTC by Illeprih

Struct for the list of shops. Named shop related variables

2022-09-24 02:58 UTC, LordMonoxide requested changes

2022-09-24 02:58 UTC, LordMonoxide commented on src/main/java/legend/game/combat/Bttl_800e.java
> +      s0.hpRegen_132.set(stats._56.get());
Hmm, what's going on with these?

2022-09-24 09:16 UTC, Illeprih commented on src/main/java/legend/game/combat/Bttl_800e.java
> +      s0.hpRegen_132.set(stats._56.get());
Apparently these values were also fixed in the battle obj. Fixed it, tested in battle and it now regenerates correctly.

2022-09-28 16:04 UTC, LordMonoxide commented on src/main/java/legend/game/SItem.java
> +  /**
Reformat javadocs and add missing *'s at the start of the lines (applies to multiple multi-line javadocs in this PR)

2022-09-28 16:04 UTC, LordMonoxide commented on src/main/java/legend/game/SItem.java
> +      v1 = worldMapNames_8011c1ec.get((int) continentIndex_800bf0b0.get()).deref();
No spaces after cast

2022-09-28 16:05 UTC, LordMonoxide commented on src/main/java/legend/game/SMap.java
> +import legend.game.types.*;
Please reconfigure your IDE to not use * imports

2022-09-28 16:06 UTC, LordMonoxide commented on src/main/java/legend/game/combat/types/BattleStructEF4/AdditionExtra04.java
> +     <ul>
Same as javadoc formatting I mentioned before

2022-09-28 16:07 UTC, LordMonoxide requested changes

2022-09-28 16:07 UTC, LordMonoxide commented on src/main/java/legend/game/combat/types/BattleStructEF4/SpecialEffects20.java
> +    /**
Same as javadoc formatting I mentioned before

2022-09-28 16:07 UTC, LordMonoxide commented on src/main/java/legend/game/combat/types/BattleStructEF4/SpecialEffects20.java
> +     <ul>
Same as javadoc formatting I mentioned before

2022-09-28 16:07 UTC, LordMonoxide commented on src/main/java/legend/game/combat/types/BattleStructEF4/Status04.java
> +    Does not decrease on all statuses
Same as javadoc formatting I mentioned before

2022-09-28 16:07 UTC, LordMonoxide commented on src/main/java/legend/game/combat/types/BattleStructEf4.java
> +   <ul>
Same as javadoc formatting I mentioned before

2022-09-28 16:07 UTC, LordMonoxide commented on src/main/java/legend/game/types/ScriptState.java
> +   <ul>
Same as javadoc formatting I mentioned before

2022-10-01 15:46 UTC, merged