Renamed some stuff
Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java pull request #117
Opened 2022-10-01 14:56 UTC by theflyingzamboni

That's it

2022-10-01 15:39 UTC, LordMonoxide requested changes

2022-10-01 15:39 UTC, LordMonoxide commented on src/main/java/legend/game/combat/Bttl_800f.java
> +  public static void drawUITextureElement(final long x, final long y, final long u, final long v, final long w, final long h, final long a6, final long a7, final long a8) {
Change `UI` to `Ui`

2022-10-01 15:39 UTC, LordMonoxide commented on src/main/java/legend/game/combat/Bttl_800f.java
> +  public static void drawItemMenuElements() {
Can you clarify if by "elements" you mean dark, fire, etc. or do you mean parts of the menu?

2022-10-02 03:08 UTC, theflyingzamboni commented on src/main/java/legend/game/combat/Bttl_800f.java
> +  public static void drawItemMenuElements() {
By elements, I mean the elements of the item menu (well, item and dragoon magic, actually). Meaning list background and text, description background and text, and MP cost background and text except the number itself. None of those will render if you comment out that method.

2022-10-06 00:18 UTC, LordMonoxide approved these changes

2022-10-06 00:19 UTC, merged