Adding some comment descriptions to Functions/Methods in Bttl_800e 0.1
Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java pull request #176
Opened 2022-12-08 14:21 UTC by dragoonsouls

Just adding some comments to some methods, following the method of breakpoint, i cannot discard the usage of some of those commented methods in other DEFF, but in most of the case i literally test in much of the Dragoon Transformations and Spells

2022-12-12 22:50 UTC, LordMonoxide requested changes

2022-12-12 22:50 UTC, LordMonoxide commented on src/main/java/legend/game/combat/Bttl_800e.java
> +  /** Get the ambient Light (start of battle) */
This is backwards, it's setting light

2022-12-12 22:50 UTC, LordMonoxide commented on src/main/java/legend/game/combat/Bttl_800e.java
> +  /** Maybe returning the Ambient light values during transformation? or is an additional screen flash during Dart Transform */
Also backwards, this is the a proxy so that the script engine can call the previous lighting method

2022-12-12 22:50 UTC, LordMonoxide commented on src/main/java/legend/game/combat/Bttl_800e.java
> +  /** Calculating FLAT light */
Also changes the projection plane distance

2022-12-12 22:50 UTC, LordMonoxide commented on src/main/java/legend/game/combat/Bttl_800e.java
> +  /** Reseting Lights after entering battle */
That's only a small part of what this does, it's also allocating the combat manager script

2022-12-12 22:50 UTC, LordMonoxide commented on src/main/java/legend/game/combat/Bttl_800e.java
> +  /** Getting Flat Light - when finishing loading */
Setting

2022-12-13 01:14 UTC, dragoonsouls commented on src/main/java/legend/game/combat/Bttl_800e.java
> +  /** Getting Flat Light - when finishing loading */
i will cancel this pull request due to not achive the minimum standards, when i get them well i will try another pull

2022-12-13 01:15 UTC, closed without merging