More debugger options and fixes
Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java pull request #243
Opened 2023-02-07 21:14 UTC by Zychronix

2023-02-07 22:17 UTC, LordMonoxide requested changes

2023-02-07 22:17 UTC, LordMonoxide commented on src/main/java/legend/game/combat/SEffe.java
> +                  if (Config.autoAddition()) {
Extra space

2023-02-07 22:17 UTC, LordMonoxide commented on src/main/resources/legend/game/debugger/debugger.fxml
> +<?import javafx.scene.layout.*?>
Is intellij still collapsing these even with the formatter changes?

2023-02-07 22:17 UTC, LordMonoxide commented on src/main/java/legend/core/Config.java
> +  public static void toggleBattleUIColour() { properties.setProperty("battle_ui_colour_change", String.valueOf(!changeBattleRGB())); }
I would prefer to have these on different lines to minimize diffs if they change

2023-02-07 22:32 UTC, Zychronix commented on src/main/java/legend/game/combat/SEffe.java
> +                  if (Config.autoAddition()) {
removed extra space

2023-02-07 22:33 UTC, Zychronix commented on src/main/resources/legend/game/debugger/debugger.fxml
> +<?import javafx.scene.layout.*?>
IntelliJ automatical does this, maybe scenebuild one of the two. Imports added back.

2023-02-07 22:33 UTC, Zychronix commented on src/main/java/legend/core/Config.java
> +  public static void toggleBattleUIColour() { properties.setProperty("battle_ui_colour_change", String.valueOf(!changeBattleRGB())); }
All on new lines now.

2023-02-08 00:25 UTC, Zychronix commented on src/main/java/legend/game/combat/SEffe.java
> +                  if (Config.autoAddition()) {
Updated again

2023-02-10 00:58 UTC, closed without merging