New Input System
Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java pull request #268
Opened 2023-02-25 02:17 UTC by LatchGameDev

- Support for over 1800+ different controllers
- F9 Will let you change what is the active controller
- Automatically assigns default bindings if only one controller is connected
- Removed old input to hex code 
- Replaced some input hex checks in the game with the new system
- Modified screens to use the new input

Example Checks:
`if(Input.pressedThisFrame (InputAction.BUTTON_NORTH)) { }
 if(Input.pressedWithRepeatPulse(InputAction.DPAD_DOWN)) { }
 if(Input.releasedThisFrame(InputAction.BUTTON_SHOULDER_LEFT_2)) { }
`

Also created event versions of these for the screens.

2023-02-25 05:03 UTC, Ink230 commented
Some testing for insight.

Main Ingame Menu
• Config submenu has no functionality
• List submenu displays active bar on both Armed item and Used item when moving between them (compared to Goods menu)
• Diig menu has no support (?fine?)
• The main in-game menu aside from the above is fully navigable: use it sub menu left/right to navigate to

Combat
• combat bar works with navigation and selection
• item menu navigation and navigation works
• daddition menu works, dmagic menu works

NPC chats
• Seem to all work as expected 

Detection
 • Detected my Xbox 360, SNES Classic controller, PS2 3rd party controller
 
 Behaviour
 • Controller input is active when LoD window is out of focus
 
 Great PR. ✔

2023-02-25 16:48 UTC, LatchGameDev commented
Thanks for taking the time to test it. When I started implementing the new system I spotted those issues and I've checked on main and most of them are there. Of course I might have messed something up locally so can you check out main and see if those issues are present when using the keyboard? 

I'm also getting a crash by using the controller/keyboard to go to the bottom of the goods screen. Can you also check if this is happening for you on this branch + main.

2023-03-04 13:45 UTC, Ink230 commented
Posting in here temporarily to remain scoped to the unmerged PR. 

Since some behaviour to the menus was added that the main branch does not have, thought it best to compile what the "state" of the menu input and behaviour functionality is with this PR. This list includes input functionality, input behaviour, and visual behaviour.

We can use this as a reference for future updates to make the menu system feature complete. I'm volunteering to see this through after the PR is merged. When the PR is merged, will link this comment to an Issue with the following text, since multiple PRs may be needed to rectify all outstanding issues.

### Menu State
These are the current issues preventing the menu screen from being fully supported and implemented for keyboard, controller, and mouse inputs. Behaviour issues are also included for conciseness.

✔ => Full support for keyboard, controller, mouse with all subsequent behaviour implemented

### General Issues
• Input still inputs when window unfocused
• • need toggle option (config), default focused only
• Circle button behaviour missing in various menus

### Main Menu
• Navigation between left and right menus is clunky
• Visual highlight appears on both, only one needed
• Grey out behaviour is not coded 

### Base Menus
Status ✔
• input held down doesn't auto scroll left or right 
Armed ✔
Addition ✔
Replace ✔
Config
• mouse only support
Save in-game menu
• full support in base menu 
• overwrite save, no circle back support
• load save, no circle back support

### Submenus
Use it ✔
• any key will close "Nothing happens" screen
List
• will be fully supported (and behaviour fixed) on merge after one quick commit (@LatchGameDev)
Goods
• keyboard support
• no controller support
• no circle back behaviour
Dabas Diig
• no keyboard support
• no controller support
• mouse support only 

### World Map ✔
### Inline menus ✔

2023-03-04 17:29 UTC, LordMonoxide requested changes

2023-03-04 17:29 UTC, LordMonoxide commented on src/main/java/legend/game/input/InputControllerData.java
> +    for(int i = 0; i < 10; i++) {
When controller is connected, probe the number of buttons and cache that value so we aren't generating many exceptions per frame. We should be able to remove all exception handling in the next few methods

2023-03-04 17:29 UTC, LordMonoxide commented on src/main/java/legend/game/input/InputPlayerUtility.java
> +  public static void update()
CS: braces on same line

2023-03-04 17:29 UTC, LordMonoxide commented on src/main/java/legend/game/input/TestInput_CheckStyle.java
> +package legend.game.input;
Remove test class

2023-03-04 17:29 UTC, LordMonoxide commented on src/main/java/legend/game/inventory/screens/EquipmentScreen.java
>    protected void keyPress(final int key, final int scancode, final int mods) {
Remove all of these empty keyPress methods

2023-03-04 17:30 UTC, LordMonoxide commented on .idea/.gitignore
> +
Revert this

2023-03-05 17:16 UTC, LatchGameDev commented on src/main/java/legend/game/fmv/Fmv.java
> +      if(Input.pressedThisFrame(InputAction.BUTTON_CENTER_2)) {
I changed it to be any button for the FMV that plays at the start but thought it would be too easy for someone to accidently skip a FMV during the game. So during the game cutscenes it's now set to skip with the select/back button.

2023-03-05 17:22 UTC, LatchGameDev commented on src/main/java/legend/game/input/ControllerDatabase.java
> +    final String textLabel = getTextCodeLabel(inputBinding.getInputAction());
Modified to prevent crash by checking the length before accessing the array.

2023-03-05 17:28 UTC, LatchGameDev commented on src/main/java/legend/game/input/ControllerDatabase.java
> +  private static int getHexCode(final InputAction targetInputAction)
What's the issue with the code snippet above? When I ctrl+alt+l the function above and below this nothing changes.

2023-03-05 17:32 UTC, LatchGameDev commented on src/main/java/legend/game/input/InputBinding.java
> +  public InputBinding(final InputAction inputAction)
I changed it to this, is this correct?

`  private final float[] pulseTimings = {
    0.5f, 0.1f
  };`

2023-03-05 22:15 UTC, Ink230 commented
![image](https://user-images.githubusercontent.com/29797557/222988832-e72e8adc-a725-4c0e-bbc5-8ad266557697.png)

Shop menu, Sell, Hover on items, Circle to go back => Crash

2023-03-05 22:17 UTC, Ink230 commented
Pressing Circle in Shop Menu, Sell, Armed => When you have no Armed items and press circle you get the notice you have no Armed items but it puts you into your Items sell interface regardless

2023-03-05 22:21 UTC, LatchGameDev commented on src/main/java/legend/game/fmv/Fmv.java
> +      if(Input.pressedThisFrame(InputAction.BUTTON_CENTER_2)) {
Corrected to Start and face buttons as requested in discord.

2023-03-05 22:25 UTC, Ink230 commented
![image](https://user-images.githubusercontent.com/29797557/222989348-5804c73b-fb88-4db0-9549-7b9560b15a21.png)


Shop, Sell, Item/Armed doesn't matter, select an item to sell
• Hit circle/back on Yes => no crash
• Hit circle/back on No => crash with above error

2023-03-06 08:10 UTC, Ink230 commented on src/main/java/legend/game/inventory/screens/MainMenuScreen.java
> +        if(this.selectedConfigOption < 0){this.selectedConfigOption = 0;}
CS

```
if () { 

}
```

2023-03-06 08:10 UTC, Ink230 commented on src/main/java/legend/game/inventory/screens/MainMenuScreen.java
> +        if(this.selectedConfigOption > 3){this.selectedConfigOption = 3;}
CS

```
if () { 

}
```

2023-03-07 12:44 UTC, LordMonoxide requested changes
Functionality issues noticed:
- On the world map, after zooming out I can't zoom back in with controller
- On the world map, if you click "no entry" when trying to enter an area, the location names become stuck on as if you're holding down start. They stay visible until you press and release start. This happens on both keyboard and controller. In this instance, they shouldn't pop up at all.

2023-03-07 12:44 UTC, LordMonoxide commented on src/main/java/legend/game/Scus94491BpeSegment.java
> +      final boolean isWindowActive = glfwGetWindowAttrib(GPU.window().getWindow(), GLFW.GLFW_FOCUSED) == GLFW.GLFW_TRUE;
Code outside of Window shouldn't need to be aware of the GLFW internals - make this an accessor on the Window class (isWindowActive(), alongside getWidth(), getHeight(), getScale()), and remove the getWindow() method that was added to Window

2023-03-07 12:44 UTC, LordMonoxide commented on src/main/java/legend/game/input/ControllerDatabase.java
> +        LOGGER.info(CONTROLLER_VERBOSE_MARKER,"Found a match for text label %s with data %s", textLabel, mapLabelAndData[1]);
```suggestion
        LOGGER.info(CONTROLLER_VERBOSE_MARKER, "Found a match for text label %s with data %s", textLabel, mapLabelAndData[1]);
```

2023-03-07 12:44 UTC, LordMonoxide commented on src/main/java/legend/game/input/InputControllerAssigner.java
> +        LOGGER.info(INPUT_MARKER,"Button motion detected with controller %s",controllerData.getInfoString());
```suggestion
        LOGGER.info(INPUT_MARKER, "Button motion detected with controller %s", controllerData.getInfoString());
```

2023-03-07 12:44 UTC, LordMonoxide commented on src/main/java/legend/game/input/InputControllerAssigner.java
> +        LOGGER.info(INPUT_MARKER,"Assigning as player %d",assignedControllers.size());
```suggestion
        LOGGER.info(INPUT_MARKER, "Assigning as player %d", assignedControllers.size());
```

2023-03-07 12:44 UTC, LordMonoxide commented on src/main/java/legend/game/input/InputControllerAssigner.java
> +          LOGGER.info(INPUT_MARKER,"Please press the buttons for player %d",assignedControllers.size() + 1);
```suggestion
          LOGGER.info(INPUT_MARKER, "Please press the buttons for player %d", assignedControllers.size() + 1);
```

2023-03-07 12:44 UTC, LordMonoxide commented on src/main/java/legend/game/input/InputControllerAssigner.java
> +      LOGGER.info(INPUT_MARKER,"Target controller count of %d reached",desiredControllerCount);
```suggestion
      LOGGER.info(INPUT_MARKER, "Target controller count of %d reached", desiredControllerCount);
```

2023-03-07 12:44 UTC, LordMonoxide commented on src/main/java/legend/game/input/InputControllerAssigner.java
> +      LOGGER.info(INPUT_MARKER,"No more controllers detected. Continuing with the %d assigned controllers ",assignedControllers.size());
```suggestion
      LOGGER.info(INPUT_MARKER, "No more controllers detected. Continuing with the %d assigned controllers ", assignedControllers.size());
```

2023-03-07 12:44 UTC, LordMonoxide commented on src/main/java/legend/game/input/InputControllerAssigner.java
> +      LOGGER.warn(INPUT_MARKER,"Failed to save config");
```suggestion
      LOGGER.warn(INPUT_MARKER, "Failed to save config");
```

2023-03-07 12:44 UTC, LordMonoxide commented on src/main/java/legend/game/input/InputControllerData.java
> +      LOGGER.error(INPUT_MARKER,"Attempting to reach out of bounds with button using glfwcode %d",glfwCode);
```suggestion
      LOGGER.error(INPUT_MARKER, "Attempting to reach out of bounds with button using glfwcode %d", glfwCode);
```

2023-03-07 12:44 UTC, LordMonoxide commented on src/main/java/legend/game/input/InputControllerData.java
> +      LOGGER.error(INPUT_MARKER,"Attempting to reach out of bounds with axis using glfwcode %d", glfwCode);
```suggestion
      LOGGER.error(INPUT_MARKER, "Attempting to reach out of bounds with axis using glfwcode %d", glfwCode);
```

2023-03-07 12:44 UTC, LordMonoxide commented on src/main/java/legend/game/input/InputControllerData.java
> +      LOGGER.error(INPUT_MARKER,"Attempting to reach out of bounds with hat index %d glfwcode %d",hatIndex,glfwCode);
```suggestion
      LOGGER.error(INPUT_MARKER, "Attempting to reach out of bounds with hat index %d glfwcode %d", hatIndex, glfwCode);
```

2023-03-07 12:55 UTC, Ink230 commented
Too Many Items Dialogue / MsgBox 

Main Branch
• Can be softlocked in the confirmation dialogue by pressing the right combination of input until you press ESC

PR
• By pressing circle, you can keep the Confirmation box from closing indefinitely
• After letting it close, there is a weird 1 frame re-render after pressing ESC / Circle / D again 

Issue is most likely that the autoclosing message boxes do not handle the state of the menu properly nor is the animation time respected by the input system. The delegate of where confirmation dialogues are passed have no code to handle anything. Thus the default implementation has been superseded by implementations elsewhere in the menu system.

2023-03-07 21:51 UTC, LatchGameDev commented on src/main/java/legend/game/Scus94491BpeSegment.java
> +      final boolean isWindowActive = glfwGetWindowAttrib(GPU.window().getWindow(), GLFW.GLFW_FOCUSED) == GLFW.GLFW_TRUE;
I believe I have made the necessary changes. Ink thought he lost permission to my repo so he messaged me the required changes.

2023-03-08 13:38 UTC, Ink230 commented
> Functionality issues noticed:
> 
> * On the world map, after zooming out I can't zoom back in with controller
> * On the world map, if you click "no entry" when trying to enter an area, the location names become stuck on as if you're holding down start. They stay visible until you press and release start. This happens on both keyboard and controller. In this instance, they shouldn't pop up at all.


1) 
To zoom in on the menu, on an Xbox 360 controller, the right joystick RIGHT movement is counted as BUTTON_SHOULDER_LEFT_2 and zooms you in. The LEFT TRIGGER seems to never be detected as an input.

This likely to be a input binding / mapping issue from the controller loading code.

2)
This seems to just be an overloading of input without a check for the context of where the input is pressed.
Line 238 may not be needed or the ENTER key should be remapped.

```
221    playerOne.addBinding(new InputBinding(InputAction.BUTTON_CENTER_2, GLFW_KEY_ENTER, 0x800, InputType.KEYBOARD));
...
238    playerOne.addBinding(new InputBinding(InputAction.BUTTON_SOUTH, GLFW_KEY_ENTER, 0x20, InputType.KEYBOARD));
```

Pretty sure this duplicated behaviour is the main issue.

2023-03-09 13:29 UTC, Ink230 commented
For commit https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/pull/268/commits/83bc1fe537d84486c888467b94d4637f0223c4a9: 

• Was this a singular issue to the specific controller? 
• Was this an issue from us or from the db having an invalid entry?
• Why would the other controllers not encounter this issue? 
• Is there a way (test framework) to ensure all the other button mappings map correctly or is this not a concern?

2023-03-09 20:53 UTC, merged