Auto Alert Icon - Quality of life improvement
Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java pull request #277
Opened 2023-02-26 05:20 UTC by LatchGameDev

Made it so the alert icon is shown briefly when selecting a script from the Smap debugger. This makes it faster to identify the relevant script the user is looking for.

2023-03-15 21:17 UTC, Ink230 commented
1) Rebase your fork branch to be at the tip or closer to the head of the current main branch. 150 commits is a lot. Then test it again to make sure it works.
![image](https://user-images.githubusercontent.com/29797557/225442620-1050542c-d2b5-44ed-88b0-48d7c90ff950.png)

2) I'm currently getting this error, even after having fresh files. This does not occur on main.
![image](https://user-images.githubusercontent.com/29797557/225442746-6929d0d1-b520-4434-a8a8-28016adeb029.png)

3) Other than that it works AND follows the XYZ of the script✔
![image](https://user-images.githubusercontent.com/29797557/225443449-fae4733a-4881-4d98-bdf7-b2c5ad4f14bd.png)

### Questions

1. It does not work with the player submap object. Or the icon at least does not appear. Is this intentional? Are there any other submap objects it will not work with?

2023-03-15 21:19 UTC, Ink230 commented on src/main/java/legend/game/debugger/SmapDebuggerController.java
> +    LOGGER.error(this.alertIconOriginalState);
LOGGER not apart of the class type w/ markers

2023-04-03 03:48 UTC, Ink230 commented
![image](https://user-images.githubusercontent.com/29797557/229406940-f33fab25-258f-4fbe-a318-0ad223ae4003.png)

These errors are output to console but the game does not crash.
Should be a warning or a regular log if no crash involved. 
If its suppose to crash, make it crash.

Not sure what purpose they have being logged.

2023-04-04 22:44 UTC, LatchGameDev commented
> ![image](https://user-images.githubusercontent.com/29797557/229406940-f33fab25-258f-4fbe-a318-0ad223ae4003.png)
> 
> These errors are output to console but the game does not crash. Should be a warning or a regular log if no crash involved. If its suppose to crash, make it crash.
> 
> Not sure what purpose they have being logged.

Sorry about that, the logged errors have accidently been committed. There were just easy to see messages to myself when I was debugging/coding which should have been removed before it left my local branch. 

Let's put the code review on pause. Still got a bit of work to do on this. Will follow up with a DM to you (Ink) for additional questions.

2023-04-05 18:41 UTC, LatchGameDev commented
> 1. It does not work with the player submap object. Or the icon at least does not appear. Is this intentional? Are there any other submap objects it will not work with?

I was testing it on maps where it did work with the player, so no it's not intentional. My code just turns it on or off so this should have been an existing issue before I made my changes. I'll see if I can track down what's going on.

2023-04-05 19:37 UTC, LordMonoxide commented
> > 1. It does not work with the player submap object. Or the icon at least does not appear. Is this intentional? Are there any other submap objects it will not work with?
> 
> I was testing it on maps where it did work with the player, so no it's not intentional. My code just turns it on or off so this should have been an existing issue before I made my changes. I'll see if I can track down what's going on.

It won't work on any map where Dart can normally have the indicator appear over his head because the scripts are constantly setting it to false

2023-04-05 19:43 UTC, LatchGameDev commented
> It won't work on any map where Dart can normally have the indicator appear over his head because the scripts are constantly setting it to false

Ah ok since that is the case then I think this is ready for a re-review / merge.

2023-04-06 03:22 UTC, Ink230 requested changes
![image](https://user-images.githubusercontent.com/29797557/230257802-175e919c-1e62-49c1-84d1-c603b678a0d6.png)

Looking good. It's able to track entities as they move. ✔

Left some comments for the code itself.

Additional stuff that probably doesn't need to block the merge but should be considered.

A toggle to:
• close all alert icons if the smap debugger is closed
• retain alerts on specific screens (after screen leaving and re-entering)

Could be useful in the future for future modders.

2023-04-06 03:22 UTC, Ink230 commented on src/main/java/legend/game/debugger/SmapDebuggerController.java
> +  private void setToOriginalState() {
```
if(this.sobj == null) return;

boolean isSelected = !this.alertIconOriginalState;
this.alertIcon.setSelected(isSelected);
this.sobj.showAlertIndicator_194 = isSelected;
```

then u can remove turnon and turnoff methods. See comment below.

2023-04-06 03:22 UTC, Ink230 commented on src/main/java/legend/game/debugger/SmapDebuggerController.java
> +      this.alertIconOriginalState = this.alertIcon.isSelected();
If you can use this.alertIcon.isSelected() to find true or false on the state of the button...why do you need a private boolean property alertIconOriginalState? And elsewhere like line 195.

2023-04-09 22:43 UTC, LatchGameDev commented on src/main/java/legend/game/debugger/SmapDebuggerController.java
> +  private void delayedSetToOriginalState() {
I originally added it for code readability. I was concerned me or someone else would wonder why the function call was seemingly delayed. Then once they traced back the call they would see the timeout executor. I also considered leaving a comment but I'd rather have it communicated in the code itself. That was my reasoning at the time but I'll remove the unnecessary function as requested.

2023-04-09 22:49 UTC, LatchGameDev commented on src/main/java/legend/game/debugger/SmapDebuggerController.java
> +  private void turnOffAlertIcon() {
That was for code readability but I removed the turn off / turn off function and put them inside the setOrClearAlertIcons() function as requested. 

` private void setOrClearAlertIcons() {
    if(this.alertIconOriginalState) {
      if(this.sobj != null) {
        this.alertIcon.setSelected(true);
        this.sobj.showAlertIndicator_194 = true;
      }
    } else {
      if(this.sobj != null) {
        this.alertIcon.setSelected(false);
        this.sobj.showAlertIndicator_194 = false;
      }
    }
  }`

2023-04-09 23:01 UTC, LatchGameDev commented on src/main/java/legend/game/debugger/SmapDebuggerController.java
> +      this.alertIconOriginalState = this.alertIcon.isSelected();
Because I was updating the UI I needed something to keep track of the true state. But if I'm no longer keeping the UI updated as you're suggesting then yes I should be able to eliminate the private boolean property alertIconOriginalState.

2023-04-09 23:11 UTC, LatchGameDev commented on src/main/java/legend/game/debugger/SmapDebuggerController.java
> +  private void setToOriginalState() {
This to me just looks like a toggle. Like it will flip the icon from whatever state it was before. Looking at the code closer there are certain instances where I just immediately want to turn off the icon. Like when the user is quickly flipping between the objects and the icon isn't being shown for the full amount of time.

2023-04-09 23:29 UTC, LatchGameDev commented on src/main/java/legend/game/debugger/SmapDebuggerController.java
> +    executorService.schedule(this::delayedSetToOriginalState, 1000, TimeUnit.MILLISECONDS);
See https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/pull/277#discussion_r1161351528

2023-04-09 23:34 UTC, LatchGameDev commented
Disregard previous comments that you may have seen. I deleted them and rolled back my local copy. I'll try to clean up the code where I can and list the reasons for each change once the rewrite is done.

2023-04-10 00:40 UTC, LatchGameDev commented
@Ink230  As I started implementing your suggested changes I kept coming across the reasons I made it this way in the first place. So I've cleaned up the code a little bit and commented the code. Basically I'm responding to the GitHub comments with code comments. This is so you can see my thought process / reasons why I did what I did. In this instance I find this easier/cleaner then making a bunch of github comments here. I can remove the code comments before it gets merged to main since comments tend to eventually get outdated.

2023-06-08 20:26 UTC, Ink230 commented
Closing until updated.

2023-06-08 20:26 UTC, closed without merging