GameState Editor & Viewer
Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java pull request #423
Opened 2023-04-15 18:21 UTC by Zychronix

2023-04-16 17:55 UTC, LordMonoxide requested changes

2023-04-16 17:55 UTC, LordMonoxide commented on src/main/java/legend/game/debugger/GameStateEditorController.java
> +    for (int i = 0; i < 0x20; i++) {
CS: no space after `for`

2023-04-16 17:55 UTC, LordMonoxide commented on src/main/java/legend/game/debugger/GameStateEditorController.java
> +    for (int i = 0; i < 0x20; i++) {
Everywhere

2023-04-16 17:55 UTC, LordMonoxide commented on src/main/java/legend/game/debugger/GameStateEditorController.java
> +    for (int i = 0; i < 0x20; i++) {
Also ifs :P

2023-04-16 17:55 UTC, LordMonoxide commented on src/main/java/legend/game/debugger/GameStateEditorController.java
> +    for (int i = 0; i < 0x20; i++) {
Also the other files

2023-04-17 02:52 UTC, Zychronix commented on src/main/java/legend/game/debugger/GameStateEditorController.java
> +    for (int i = 0; i < 0x20; i++) {
Fixed in the latest commit

2023-04-17 02:53 UTC, LordMonoxide approved these changes

2023-04-17 02:54 UTC, merged