GameState Editor Fixes and Combat Debugger HP Expansion
Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java pull request #427
Opened 2023-04-17 23:08 UTC by Zychronix

2023-04-18 01:31 UTC, Ink230 commented on src/main/java/legend/game/debugger/CombatDebuggerController.java
> +    this.maxHp.setValueFactory(new SpinnerValueFactory.IntegerSpinnerValueFactory(1, 2147483647));
Integer.MAX_VALUE or pester Monoxide for a master enum file

2023-04-18 01:31 UTC, Ink230 commented on src/main/resources/legend/game/debugger/combat_debugger.fxml
> +<VBox maxHeight="-Infinity" maxWidth="-Infinity" minHeight="-Infinity" minWidth="-Infinity" prefHeight="400.0" prefWidth="600.0" stylesheets="@script_debugger.css" xmlns="http://javafx.com/javafx/17.
Downgrade? Confident in no issues with it?

2023-04-18 02:22 UTC, Zychronix commented on src/main/resources/legend/game/debugger/combat_debugger.fxml
> +<VBox maxHeight="-Infinity" maxWidth="-Infinity" minHeight="-Infinity" minWidth="-Infinity" prefHeight="400.0" prefWidth="600.0" stylesheets="@script_debugger.css" xmlns="http://javafx.com/javafx/17.
It should be version 17, I am not sure why the editor keeps changing it for me.

2023-04-18 02:22 UTC, Zychronix commented on src/main/java/legend/game/debugger/CombatDebuggerController.java
> +    this.maxHp.setValueFactory(new SpinnerValueFactory.IntegerSpinnerValueFactory(1, 2147483647));
Changed it to Integer.MAX_VALUE

2023-04-18 02:37 UTC, Ink230 submitted a review, later dismissed
LGTM!

2023-04-21 11:07 UTC, LordMonoxide requested changes

2023-04-21 11:07 UTC, LordMonoxide commented on src/main/java/legend/game/debugger/GameStateEditorController.java
> +    }else{
```suggestion
    } else {
```

2023-04-21 11:07 UTC, LordMonoxide commented on src/main/java/legend/game/debugger/GameStateEditorController.java
> +    }else{
```suggestion
    } else {
```

2023-04-21 11:07 UTC, LordMonoxide commented on src/main/java/legend/game/debugger/GameStateEditorController.java
> +    }else{
```suggestion
    } else {
```

2023-04-21 11:07 UTC, LordMonoxide commented on src/main/java/legend/game/debugger/GameStateEditorController.java
> +    }else{
```suggestion
    } else {
```

2023-04-21 19:48 UTC, LordMonoxide approved these changes

2023-04-21 19:49 UTC, merged