Addition overlay refactor and config/debug controls
Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java pull request #465
Opened 2023-05-06 18:24 UTC by theflyingzamboni

All memory related to the addition overlay has been moved into ref structs, and related code refactored and named.

Also created a safer and less hacky implementation of auto addition, added auto-addition and addition overlay display controls to game options, and added options to control overlay colors to the debugger.

2023-05-07 17:12 UTC, Ink230 submitted a review, later dismissed

2023-05-07 17:12 UTC, Ink230 commented on src/main/java/legend/game/combat/SBtld.java
> +      final BattlePreloadedEntities_18cb0.AdditionHits100 activeAdditionHits = battlePreloadedEntities_1f8003f4.additionHits_38[charSlot];
Are we suppose to be removing the _

2023-05-07 17:12 UTC, Ink230 commented on src/main/java/legend/game/combat/environment/BattlePreloadedEntities_18cb0.java
> +  /**
A lot of line changes just for a diff comment syntax

2023-05-08 22:59 UTC, theflyingzamboni commented on src/main/java/legend/game/combat/SBtld.java
> +      final BattlePreloadedEntities_18cb0.AdditionHits100 activeAdditionHits = battlePreloadedEntities_1f8003f4.additionHits_38[charSlot];
@LordMonoxide should chime in, but I think the _ might have been an early naming convention for structs, because most of our structs don't have them.

2023-05-09 01:17 UTC, theflyingzamboni commented on src/main/java/legend/game/combat/environment/BattlePreloadedEntities_18cb0.java
> +  /**
Stupid auto-formatting. I think I changed my settings to preserve one-line docstrings, but it's not in the project file on the repo. Guess this got altered before I changed that.

2023-05-09 21:58 UTC, LordMonoxide commented on src/main/java/legend/game/combat/SBtld.java
> +      final BattlePreloadedEntities_18cb0.AdditionHits100 activeAdditionHits = battlePreloadedEntities_1f8003f4.additionHits_38[charSlot];
Either is fine, I usually only use a `_` if there are back to back numbers that need to be separated

2023-05-09 22:22 UTC, LordMonoxide requested changes

2023-05-09 22:22 UTC, LordMonoxide commented on src/main/java/legend/game/combat/Bttl_800d.java
> +    if(Config.changeAdditionOverlayRGB()) {
If you invert this `if` statement you can merge the default colour hack with an `||` so you don't need two equivalent branches

2023-05-09 22:22 UTC, LordMonoxide commented on src/main/java/legend/game/combat/SEffe.java
> +  /** Fours sets of color values used for addition overlay borders; only last actually used */
```suggestion
  /** Four sets of colour values used for addition overlay borders; only last actually used */
```

2023-05-09 22:22 UTC, LordMonoxide commented on src/main/java/legend/game/combat/SEffe.java
> +  public static final ArrayRef<UnsignedByteRef> additionBorderColors_800fb7f0 = MEMORY.ref(1, 0x800fb7f0L, ArrayRef.of(UnsignedByteRef.class, 0xc, 0x1, UnsignedByteRef::new));
```suggestion
  public static final ArrayRef<UnsignedByteRef> additionBorderColours_800fb7f0 = MEMORY.ref(1, 0x800fb7f0L, ArrayRef.of(UnsignedByteRef.class, 0xc, 0x1, UnsignedByteRef::new));
```
We use the _proper_ spelling everywhere else

2023-05-09 22:22 UTC, LordMonoxide commented on src/main/java/legend/game/modding/coremod/config/AdditionOverlayConfigEntry.java
> +    return new byte[]{(byte)val.ordinal()};
```suggestion
    return new byte[] {(byte)val.ordinal()};
```

2023-05-09 22:22 UTC, LordMonoxide commented on src/main/java/legend/game/modding/coremod/config/AutoAdditionConfigEntry.java
> +    return new byte[]{(byte)val.ordinal()};
```suggestion
    return new byte[] {(byte)val.ordinal()};
```

2023-05-09 22:22 UTC, LordMonoxide commented on src/main/java/legend/core/Config.java
> +    if(gameState_800babc8 != null) {
This effectively makes the config file value unused, since the config registry entry has a default value anyway. It will only apply on the title screen before a game is loaded, where it doesn't have meaning anyway. I'm going to be extending the config system this release to support config values that are global so the Config class will be removed anyway.

Update where these methods are being called to use the game state directly and remove the auto-addition methods here. We can leave it in the debugger for now since we don't have a way to change options in combat yet.

2023-05-09 22:32 UTC, theflyingzamboni commented on src/main/java/legend/core/Config.java
> +  public static int getAdditionOverlayRGB() {
Should I change the others while I'm at it? I was copying the existing style in that file.

2023-05-09 22:34 UTC, theflyingzamboni commented on src/main/java/legend/game/combat/SEffe.java
> +  public static final ArrayRef<UnsignedByteRef> additionBorderColors_800fb7f0 = MEMORY.ref(1, 0x800fb7f0L, ArrayRef.of(UnsignedByteRef.class, 0xc, 0x1, UnsignedByteRef::new));
Don't tempt me to change *all* of the other spellings to be consistently correct. :stuck_out_tongue:

2023-05-09 22:35 UTC, LordMonoxide commented on src/main/java/legend/core/Config.java
> +  public static int getAdditionOverlayRGB() {
Yes you might as well

2023-05-10 02:46 UTC, LordMonoxide approved these changes

2023-05-10 02:55 UTC, merged