Fixes sprite renderer called by processLmb methods
Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java pull request #481
Opened 2023-05-09 21:35 UTC by theflyingzamboni

When constructing the gp0 packet in retail, the u value is right-shifted by 6 to fit it into the low nibble of the tpage in the packet, so the lowest 6 bytes are removed when multiplying by 64 to calculate VRAM position. u is composed of VRAM X + u, so in SC, the u needed to be factored out as well.

Fixes Melbu's solar system attack and ??? other effects.

2023-05-09 22:11 UTC, Ink230 submitted a review, later dismissed
Perfect PR length.

2023-05-09 22:27 UTC, LordMonoxide requested changes

2023-05-09 22:27 UTC, LordMonoxide commented on src/main/java/legend/game/combat/SEffe.java
> +          .vramPos(((effect.metrics_54.u_00.get() & 0x3ff) & ~0x3f), (effect.metrics_54.v_02.get() & 0x100) != 0 ? 256 : 0)
```suggestion
          .vramPos((effect.metrics_54.u_00.get() & 0x3c0), (effect.metrics_54.v_02.get() & 0x100) != 0 ? 256 : 0)
```

2023-05-10 00:11 UTC, LordMonoxide approved these changes

2023-05-10 00:11 UTC, merged