Higher resolution panning
Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java pull request #633
Opened 2023-06-16 10:12 UTC by Illeprih

2023-06-16 23:40 UTC, LordMonoxide approved these changes

2023-06-16 23:41 UTC, LordMonoxide requested changes
Can `_80059b3c` be removed now?

2023-06-17 13:05 UTC, Illeprih commented
Replaced the pan volume table and removed the unnecessary Memory refs

2023-06-18 16:27 UTC, LordMonoxide approved these changes

2023-06-18 16:27 UTC, merged