Particle effects + line particle rendering bugfix
Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java pull request #660
Opened 2023-07-04 18:18 UTC by theflyingzamboni

I think the naming is in a good enough state that it makes sense to go ahead and merge this to avoid more conflicts, plus it fixes a bug now. Feel free to rename some fields and things if they don't seem quite right.

2023-07-07 02:22 UTC, Ink230 reviewed
1. This took 2 days to review.
2. Nothing silly that I can see.
3. tfz has comments for Monoxide in here.
4. Game doesn't crash when playing with this. ✔
5. SEffe.java is gross.

2023-07-08 12:46 UTC, LordMonoxide requested changes

2023-07-08 12:46 UTC, LordMonoxide commented on src/main/java/legend/game/combat/SEffe.java
> +      particle._1a.y.sub((short)8);
This struck me as odd (checking X and subtracting from Y), I did a quick check in ghidra and I'm pretty sure it's wrong

2023-07-08 12:46 UTC, LordMonoxide commented on src/main/java/legend/game/combat/SEffe.java
> +      effect.effectAcceleration_70.mul(effect.scaleParticleAcceleration_80).shra(8);
This can overflow with large values so it needs to be changed back

2023-07-08 12:46 UTC, LordMonoxide commented on src/main/java/legend/game/combat/SEffe.java
> +      effect.effectAcceleration_70.mul(effect.scaleParticleAcceleration_80).shra(8);
This may also overflow, but would have been an existing problem

2023-07-08 12:46 UTC, LordMonoxide commented on src/main/java/legend/game/combat/SEffe.java
> +      effect.effectAcceleration_70.mul(effect.scaleParticleAcceleration_80).shra(8);
Same here

2023-07-09 15:23 UTC, theflyingzamboni commented on src/main/java/legend/game/combat/SEffe.java
> +      particle._1a.y.sub((short)8);
It was wrong.

2023-07-09 20:51 UTC, LordMonoxide approved these changes

2023-07-09 20:51 UTC, merged