Bttl 800c globals
Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java pull request #674
Opened 2023-07-09 21:37 UTC by theflyingzamboni

Typed, named, and refactored as many of the globals in 800c as I could, along with quite a bit of code that uses them. Anything I refactored into a struct should probably be double-checked in-game to make sure it still works correctly. I've caught some bugs I accidentally introduced, but it's possible I missed a couple.

2023-07-10 00:17 UTC, Ink230 reviewed
Some comments just for confirming sanity.

2023-07-10 00:17 UTC, Ink230 commented on src/main/java/legend/game/Scus94491BpeSegment.java
> +  public static void renderDivineDragoonAdditionPressIris(final int x, final int y, final int u, final int v, final int width, final int height, final int clutOffset, @Nullable final Translucency tra
long to int?

2023-07-10 00:17 UTC, Ink230 commented on src/main/java/legend/game/combat/Bttl_800f.java
> +        .pos(0, leftX, topY)
Does appending X and Y to the left/right, top/bottom directions make sense in this context? If there can't be a leftY why does it need to be noted there is a leftX?

2023-07-10 23:15 UTC, LordMonoxide requested changes

2023-07-11 01:45 UTC, theflyingzamboni commented on src/main/java/legend/game/Scus94491BpeSegment_8003.java
> +    CPU.COP2(0x48_0012L); // MVMVA (translation=tr, mul vec=in, mul mat=rot, 12-bit fraction)
loooool I thought that was just another generic register variable name

2023-07-11 01:53 UTC, theflyingzamboni commented on src/main/java/legend/game/Scus94491BpeSegment.java
> +  public static void renderDivineDragoonAdditionPressIris(final int x, final int y, final int u, final int v, final int width, final int height, final int clutOffset, @Nullable final Translucency tra
They aren't addresses or int flags, so they should never over flow. From what I can see, they'd never even overflow a short.

2023-07-11 01:56 UTC, theflyingzamboni commented on src/main/java/legend/game/combat/Bttl_800f.java
> +        .pos(0, leftX, topY)
They're distinguishing e.g. topY from topV or leftX from leftU.

2023-07-13 12:45 UTC, LordMonoxide approved these changes

2023-07-13 14:14 UTC, merged