Add a lot of script metadata
Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java pull request #695
Opened 2023-08-21 23:22 UTC by LordMonoxide

2023-08-22 22:29 UTC, theflyingzamboni requested changes
A lot of the comments are repetitive just to mark the locations so you can find all the instances.

2023-08-22 22:29 UTC, theflyingzamboni commented on src/main/java/legend/game/SMap.java
> +  @ScriptParam(direction = ScriptParam.Direction.IN, type = ScriptParam.Type.INT, name = "numberOfParts", description = "The number of model parts")
1 should be OUT

2023-08-22 22:29 UTC, theflyingzamboni commented on src/main/java/legend/game/SMap.java
> +        Scus94491BpeSegment.startFadeEffect(1, 10);
Fix static import

2023-08-22 22:29 UTC, theflyingzamboni commented on src/main/java/legend/game/Scus94491BpeSegment.java
> +        final int submapIndex = submapId_800bd808.get();
Rename int to submapId for consistency?

2023-08-22 22:29 UTC, theflyingzamboni commented on src/main/java/legend/game/Scus94491BpeSegment_8002.java
> +        Scus94491BpeSegment.startFadeEffect(2, 10);
Fix static import

2023-08-22 22:29 UTC, theflyingzamboni commented on src/main/java/legend/game/combat/Bttl_800c.java
> +    Scus94491BpeSegment.startFadeEffect(4, 30);
Fix static import

2023-08-22 22:29 UTC, theflyingzamboni commented on src/main/java/legend/game/inventory/screens/AdditionsScreen.java
> +        Scus94491BpeSegment.startFadeEffect(2, 10);
Fix static import

2023-08-22 22:29 UTC, theflyingzamboni commented on src/main/java/legend/game/inventory/screens/CampaignSelectionScreen.java
> +    Scus94491BpeSegment.startFadeEffect(2, 10);
Fix static import

2023-08-22 22:29 UTC, theflyingzamboni commented on src/main/java/legend/game/inventory/screens/CharSwapScreen.java
> +        Scus94491BpeSegment.startFadeEffect(2, 10);
Fix static import

2023-08-22 22:29 UTC, theflyingzamboni commented on src/main/java/legend/game/inventory/screens/DabasScreen.java
> +        Scus94491BpeSegment.startFadeEffect(2, 10);
Fix static import

2023-08-22 22:29 UTC, theflyingzamboni commented on src/main/java/legend/game/inventory/screens/EquipmentScreen.java
> +        Scus94491BpeSegment.startFadeEffect(2, 10);
Fix static import

2023-08-22 22:29 UTC, theflyingzamboni commented on src/main/java/legend/game/inventory/screens/GoodsScreen.java
> +    Scus94491BpeSegment.startFadeEffect(2, 10);
Fix static import

2023-08-22 22:29 UTC, theflyingzamboni commented on src/main/java/legend/game/inventory/screens/ItemListScreen.java
> +    Scus94491BpeSegment.startFadeEffect(2, 10);
Fix static import

2023-08-22 22:29 UTC, theflyingzamboni commented on src/main/java/legend/game/inventory/screens/KeybindsScreen.java
> +    Scus94491BpeSegment.startFadeEffect(2, 10);
Fix static import

2023-08-22 22:29 UTC, theflyingzamboni commented on src/main/java/legend/game/inventory/screens/LoadGameScreen.java
> +    Scus94491BpeSegment.startFadeEffect(2, 10);
Fix static import

2023-08-22 22:29 UTC, theflyingzamboni commented on src/main/java/legend/game/inventory/screens/MainMenuScreen.java
> +        Scus94491BpeSegment.startFadeEffect(2, 10);
Fix static import

2023-08-22 22:29 UTC, theflyingzamboni commented on src/main/java/legend/game/inventory/screens/ModsScreen.java
> +    Scus94491BpeSegment.startFadeEffect(2, 10);
Fix static import

2023-08-22 22:29 UTC, theflyingzamboni commented on src/main/java/legend/game/inventory/screens/NewCampaignScreen.java
> +    Scus94491BpeSegment.startFadeEffect(2, 10);
Fix static import

2023-08-22 22:29 UTC, theflyingzamboni commented on src/main/java/legend/game/inventory/screens/OptionsScreen.java
> +    Scus94491BpeSegment.startFadeEffect(2, 10);
Fix static import

2023-08-22 22:29 UTC, theflyingzamboni commented on src/main/java/legend/game/inventory/screens/SaveGameScreen.java
> +    Scus94491BpeSegment.startFadeEffect(2, 10);
Fix static import

2023-08-22 22:29 UTC, theflyingzamboni commented on src/main/java/legend/game/inventory/screens/ShopScreen.java
> +          Scus94491BpeSegment.startFadeEffect(2, 10);
Fix static import

2023-08-22 22:29 UTC, theflyingzamboni commented on src/main/java/legend/game/inventory/screens/TooManyItemsScreen.java
> +        Scus94491BpeSegment.startFadeEffect(2, 10);
Fix static import

2023-08-22 22:29 UTC, theflyingzamboni commented on src/main/java/legend/game/inventory/screens/UseItemScreen.java
> +        Scus94491BpeSegment.startFadeEffect(2, 10);
Fix static import

2023-08-22 22:29 UTC, theflyingzamboni commented on src/main/java/legend/game/modding/coremod/config/ControllerKeybindsConfigEntry.java
> +        Scus94491BpeSegment.startFadeEffect(2, 10);
Fix static import

2023-08-22 22:29 UTC, theflyingzamboni commented on src/main/java/legend/game/title/GameOver.java
> +        Scus94491BpeSegment.startFadeEffect(2, 10);
Fix static import

2023-08-22 22:29 UTC, theflyingzamboni commented on src/main/java/legend/game/title/Ttle.java
> +    Scus94491BpeSegment.startFadeEffect(2, 15);
Fix static import

2023-08-22 22:29 UTC, theflyingzamboni commented on src/main/java/legend/game/wmap/WMap.java
> +                              Scus94491BpeSegment.startFadeEffect(1, 15);
Fix static import

2023-08-22 22:29 UTC, theflyingzamboni commented on src/main/java/legend/game/inventory/screens/StatusScreen.java
> +        Scus94491BpeSegment.startFadeEffect(2, 10);
Fix static import

2023-08-22 22:29 UTC, theflyingzamboni commented on src/main/java/legend/game/combat/Bttl_800d.java
> +  @ScriptParam(direction = ScriptParam.Direction.IN, type = ScriptParam.Type.INT, name = "?")
This is delta 1 in the step smoother

2023-08-22 23:58 UTC, LordMonoxide commented on src/main/java/legend/game/SMap.java
> +  public static FlowControl scriptSelfFaceCamera(final RunningScript<?> script) {
This one's done in a subsequent PR, I just happened to rename it here (doing it from the top of the subfuncs list down)

2023-08-23 00:11 UTC, LordMonoxide commented on src/main/java/legend/game/SMap.java
> +    setCameraPos(new SVECTOR().set((short)script.params_20[0].get(), (short)script.params_20[0].get(), (short)script.params_20[0].get()));
This is retail, but it's gotta be a bug... we should look into it

2023-08-23 21:45 UTC, merged