Fixed location menu ordering and added rendering for barrier station options
Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java pull request #757
Opened 2023-10-27 22:42 UTC by theflyingzamboni

Fixes #752

2023-10-28 16:48 UTC, theflyingzamboni commented on src/main/java/legend/game/wmap/WMap.java
> +        this.destPlaceNames = null;
Do I need to delete each object individually, or will nulling the array allow everything to be released and garbage collected?

2023-10-28 21:28 UTC, LordMonoxide requested changes

2023-10-28 21:28 UTC, LordMonoxide commented on src/main/java/legend/game/wmap/WMap.java
> +          this.textTransforms.transfer.setComponent(1, 182.0f);
You can just do `.y = 182.0f`

2023-10-28 21:28 UTC, LordMonoxide commented on src/main/java/legend/game/wmap/WMap.java
> +          this.textTransforms.transfer.setComponent(1, 200.0f);
Same here

2023-10-28 21:28 UTC, LordMonoxide commented on src/main/java/legend/game/wmap/WMap.java
> +        this.destPlaceNames = null;
They all need to be deleted from the GPU memory or it'll cause a GPU memory leak

2023-10-28 21:28 UTC, LordMonoxide commented on src/main/java/legend/game/wmap/WMap.java
> +            this.destPlaceNames = new TextObj[regions_800f01ec.length()];
Do we need to upload renderables for every region to the GPU? Or do we know which region we should be displaying?

2023-10-29 01:05 UTC, LordMonoxide approved these changes

2023-10-29 01:05 UTC, merged