Map Indicators
Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java pull request #947
Opened 2023-12-16 15:15 UTC by Zychronix

2023-12-16 15:57 UTC, LordMonoxide requested changes

2023-12-16 15:57 UTC, LordMonoxide commented on src/main/java/legend/game/submap/MapIndicator.java
> +      this.doorIndicator.get(index);
Instead of doing this, check if the list is empty and build all of them, or better yet build it as a single multi-quad obj

2023-12-16 15:57 UTC, LordMonoxide commented on src/main/java/legend/game/submap/MapIndicator.java
> +  public void destroy() {
CS: blank line between methods

2023-12-16 15:57 UTC, LordMonoxide commented on src/main/java/legend/game/submap/SMap.java
> +  private MapIndicator mapIndicator = new MapIndicator();
CS: final

2023-12-16 15:57 UTC, LordMonoxide commented on src/main/java/legend/game/submap/MapIndicator.java
> +  public ArrayList<Obj> doorIndicator = new ArrayList<>();
CS: final, and use List<Obj> as the type instead of ArrayList<Obj>

2023-12-16 15:57 UTC, LordMonoxide commented on src/main/java/legend/game/submap/SMap.java
> +        //GPU.queueCommand(38, cmd);
You can just remove this

2023-12-16 15:57 UTC, LordMonoxide commented on src/main/java/legend/game/submap/MapIndicator.java
> +public class MapIndicator {
CS: reformat class with project style

2023-12-16 18:58 UTC, Zychronix commented on src/main/java/legend/game/submap/SMap.java
> +        //GPU.queueCommand(38, cmd);
yeeted

2023-12-16 18:58 UTC, Zychronix commented on src/main/java/legend/game/submap/MapIndicator.java
> +      this.doorIndicator.get(index);
got rid of the array as only a single doorindicator is needed

2023-12-16 23:55 UTC, LordMonoxide requested changes

2023-12-16 23:55 UTC, LordMonoxide commented on src/main/java/legend/game/submap/MapIndicator.java
> +  public void MapIndicator() {
You can just completely delete this, they'll get build if they're null anyway. And if this is instantiated on any thread other than the main one, it'll crash due to having no GL context

2023-12-16 23:55 UTC, LordMonoxide commented on src/main/java/legend/game/submap/SMap.java
> +        if(s1.time_08 < 0 - vsyncMode_8007a3b8 && ((this.smapTicks_800c6ae0 % (2 * (3 - vsyncMode_8007a3b8))) & 1) != 0) {
This time_08 check is definitely wrong, it needs to have a multiplier based on vsyncMode

2023-12-17 00:30 UTC, Zychronix commented on src/main/java/legend/game/submap/MapIndicator.java
> +  public void MapIndicator() {
yeet

2023-12-17 00:45 UTC, Zychronix commented on src/main/java/legend/game/submap/SMap.java
> +        if(s1.time_08 < 0 - vsyncMode_8007a3b8 && ((this.smapTicks_800c6ae0 % (2 * (3 - vsyncMode_8007a3b8))) & 1) != 0) {
change to only reduce time_08 based on vsyncmode mod result

2023-12-17 00:53 UTC, LordMonoxide approved these changes

2023-12-17 00:53 UTC, merged

2023-12-17 00:55 UTC, LordMonoxide commented
Closes #925