Implemented SMAP snow effect
Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java pull request #957
Opened 2023-12-20 22:35 UTC by theflyingzamboni

- Named fields and vars
- Refactored code into own class
- Converted to floats where needed
- Implemented modern RNG to improve snow distribution
- Used shadow texture instead of plain quad for snow obj

Closes #923

2023-12-20 23:32 UTC, LordMonoxide requested changes

2023-12-20 23:32 UTC, LordMonoxide commented on src/main/java/legend/game/submap/SMap.java
> +      final float stepAngleMax = script.params_20[4].get() / 4096.0f * MathHelper.TWO_PI;
MathHelper.psxDegToRad

2023-12-20 23:32 UTC, LordMonoxide commented on src/main/java/legend/game/submap/SnowEffect.java
> +    this.particle = new QuadBuilder("Snowflake")
Having anything that communicates with the GPU in a constructor can make it tricky to instantiate the object, because it has to be done in the main thread. If we were to refactor SMAP to load in a secondary thread, for example, this would crash. That's why I usually build Objs in the render methods themselves, if they haven't been built yet, since we're guaranteed to be on the render thread there. It's a little messy, but it gets the job done.

2023-12-20 23:32 UTC, LordMonoxide commented on src/main/java/legend/game/submap/SnowEffect.java
> +      this.snowOffsetXTick = this.snowOffsetXTick + 1 & 0xf;
Are these good for variable frame rates?

2023-12-20 23:32 UTC, LordMonoxide commented on src/main/java/legend/game/submap/SnowEffect.java
> +    this.snowOffsetXTick = this.snowOffsetXTick + 1 & 0xf;
Same here, at the if statement above

2023-12-20 23:37 UTC, theflyingzamboni commented on src/main/java/legend/game/submap/SMap.java
> +      final float stepAngleMax = script.params_20[4].get() / 4096.0f * MathHelper.TWO_PI;
Derp

2023-12-21 04:25 UTC, theflyingzamboni commented on src/main/java/legend/game/submap/SnowEffect.java
> +      this.snowOffsetXTick = this.snowOffsetXTick + 1 & 0xf;
These variables only increment per particle processed, not per frame, and are only used when initializing a new particle traversal (either init or wrap).

2023-12-21 04:25 UTC, theflyingzamboni commented on src/main/java/legend/game/submap/SnowEffect.java
> +    this.snowOffsetXTick = this.snowOffsetXTick + 1 & 0xf;
See above

2023-12-21 20:49 UTC, LordMonoxide approved these changes

2023-12-21 20:49 UTC, merged