Defined AttachedSobjEffect code
Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java pull request #986
Opened 2023-12-28 02:18 UTC by theflyingzamboni

This includes various particle effects that act as trails for sobj's, such as dust, footprints, and law pod trails. All related code should be named now.

2023-12-28 03:22 UTC, LordMonoxide requested changes

2023-12-28 03:22 UTC, LordMonoxide commented on src/main/java/legend/game/submap/SMap.java
> +      metrics.x_10 = this.submapOffsetX_800cb560 + this.screenOffsetX_800cb568 + metrics.offsetX_1c;
Did you mean to commit this?

2023-12-28 03:22 UTC, LordMonoxide commented on src/main/java/legend/game/submap/SMap.java
> +  @ScriptParam(direction = ScriptParam.Direction.IN, type = ScriptParam.Type.INT, name = "shouldDeallocate", description = "Deallocate trail effect when true.")
You can set the type for vars like this to BOOL

2023-12-29 01:44 UTC, theflyingzamboni commented on src/main/java/legend/game/submap/SMap.java
> +      metrics.x_10 = this.submapOffsetX_800cb560 + this.screenOffsetX_800cb568 + metrics.offsetX_1c;
Yes. There are some effects I can't see on a black background when I'm checking SW mode.

2023-12-29 02:38 UTC, LordMonoxide approved these changes

2023-12-29 02:38 UTC, merged